### ISSUE TITLE
nlf-r 0 does not work

### ISSUE THREAD

**Issue by MitchK** [iandotkelly/nlf#46]
I only want to print top level licenses, but 
```
nlf -r 0
```

Does not limit the dependencies. Thanks.

**Comment by iandotkelly** [comment]
This is because npm changed how it worked and now flattens the dependency structure.  I'm looking at changing how nlf determines the 'depth'.

I would say however that the legal basis of only looking at the top level is somewhat suspect anyway.  You're bundling *all* the node modules in your application, and almost the entire purpose of nlf is to uncover the hidden dependencies of dependencies that you pick up.

**Comment by iandotkelly** [comment]
Fixed with https://github.com/iandotkelly/nlf/releases/tag/2.0.0
